name: Spring Reactive Build

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest  # Recommended for Java builds

    services:
      mongodb:
        image: mongo:6.0
        ports:
          - 27017:27017

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven (skip tests)
        run: mvn -B clean package -DskipTests

      - name: Run Tests
        env:
          SPRING_DATA_MONGODB_URI: mongodb://localhost:27017/emsDB
        run: mvn test
